# Generated by Django 3.0 on 2022-01-26 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20220126_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 19, 6, 2, 314992)),
        ),
    ]
