# Generated by Django 3.0 on 2022-01-26 15:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0009_auto_20220126_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 15, 46, 40, 636502, tzinfo=utc)),
        ),
    ]
