# Generated by Django 3.0 on 2022-01-26 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0010_auto_20220126_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
