# Generated by Django 3.0 on 2022-01-30 14:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0011_auto_20220126_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='reciver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reciver', to='message.UserProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messages',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 18, 2, 47, 964891)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='message.UserProfile'),
        ),
    ]
